### ISSUE TITLE
Does this project work with SNS destinations?

### ISSUE THREAD

**Issue by DarthHater** [aws/aws-lambda-go#290]
I have been struggling with a Golang lambda all day (which works great, until....) and I can't quite get it work with publishing to an SNS Topic via the Destination feature.

My handler looks akin to:

`func handler(ctx context.Context, sqsEvent events.SQSEvent) (Response, error) {`

`Response` is a struct with four strings on it, marked for how I want them to be serialized (all of the properties start with an upper case letter, so they are public)

If I execute the Lamba, I can see a response, which is proper JSON that I expect (so it looks like it serializes fine).

The SNS topic I have setup has SNS:Publish given to the role executing the lambda, and the lambda has SNS:publish to the topic's ARN.

A coworker and I were able to get a node.js test lambda to publish to the SNS topic, so we are scratching our heads at this one.

I'm using `1.16.0` of this library, Golang `1.14.2`, Mac OS X `10.15.4`, building with `GOOS=linux` and my code (minus the actual code I wrote) looks more or less like this:

```
package main

import (
        "fmt"
        "context"
        "github.com/aws/aws-lambda-go/lambda"
        "github.com/aws/aws-lambda-go/events"
)

type Response struct {
        Name string `json:"name"`
}

func main() {
        lambda.Start(handler)
}

func handler(ctx context.Context, sqsEvent events.SQSEvent) (Response, error) {
        response := Response{Name: "name"}
        return response, nil
}
```

**Comment by mhart** [comment]
I'm guessing you want `SNSEvent`, not `SQSEvent` 😸 

https://github.com/aws/aws-lambda-go/blob/master/events/README_SNS.md

**Comment by DarthHater** [comment]
> I'm guessing you want `SNSEvent`, not `SQSEvent` 😸
> 
> https://github.com/aws/aws-lambda-go/blob/master/events/README_SNS.md

Nope. I receive an SQS event, and I'm looking to publish the result of transforming it into another format as a SNS Topic, using the SNS topic Destination.

**Comment by mhart** [comment]
Ah, my bad – I couldn't see any SNS code in your sample

**Comment by msmagoo87** [comment]
> Ah, my bad – I couldn't see any SNS code in your sample

The co-worker he mentioned here. You don't see SNS in the code because he is using the Lambda Destination feature (https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/) which should be able to receive a json output and pipe that to an SNS topic. AWS takes care of this and it shouldn't need any SNS references in the actual code.

**Comment by mhart** [comment]
Just confirming you're testing the Lambda with an asynchronous invocation (invocation type Event) and not a synchronous one (using the web console only trigger synchronous events)?

**Comment by mhart** [comment]
FWIW, the following works for me.

SAM template.yaml:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DestinationFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: destination-test/
      Handler: destination-test
      Runtime: go1.x
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SNS
            Destination: !Ref DestinationTopic
          OnFailure:
            Type: SNS
            Destination: !Ref DestinationTopic

  DestinationTopic:
    Type: AWS::SNS::Topic

  DestinationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: myemail@domain.com
      Protocol: email
      TopicArn: !Ref DestinationTopic

Outputs:
  DestinationFunction:
    Value: !GetAtt DestinationFunction.Arn
```

main.go:
```go
package main

import (
	"github.com/aws/aws-lambda-go/lambda"
)

func handler(request interface{}) (string, error) {
	return "success", nil
}

func main() {
	lambda.Start(handler)
}
```
After `sam build` and `sam deploy`, I then do this:
```console
aws lambda invoke --function-name <name> --invocation-type Event --payload '{}' /dev/stdout
```
And I receive an email along the lines of this:
```json
{
  "version": "1.0",
  "timestamp": "2020-05-12T15:23:21.725Z",
  "requestContext": {
    "requestId": "d7a382da-dda9-46c7-85cc-9c1aa7b62f31",
    "functionArn": "arn:aws:lambda:us-east-1:<arn>:$LATEST",
    "condition": "Success",
    "approximateInvokeCount": 1
  },
  "requestPayload": {},
  "responseContext": {
    "statusCode": 200,
    "executedVersion": "$LATEST"
  },
  "responsePayload": "success"
}
```
