### ISSUE TITLE
json: cannot unmarshal object into Go struct field APIGatewayProxyRequest.body of type string on GET request

### ISSUE THREAD

**Issue by kendrickkesley** [aws/aws-lambda-go#68]
Hi,

I'm getting `{"errorMessage":"json: cannot unmarshal object into Go struct field APIGatewayProxyRequest.body of type string","errorType":"UnmarshalTypeError"}` in the response when using a `GET` method from api gateway

`func Handler(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error)`

Do you know why it happens?

**Comment by kendrickkesley** [comment]
it turns out it's because I did not use lambda proxy integration. My bad.

**Comment by m1ch3lp3r3z** [comment]
Hi @kkesley I'm having the same issue after enabling lambda integration in my serverless.yml, because I need it for custom status codes (302). Could you please describe little more how you solved the problem?. Thank you!

**Comment by kkesley** [comment]
Hi @m1ch3lp3r3z TBH I made a mistake by not providing any details to my issue and I forgot about the issue I was having. Can you provide an example for your serverless.yml detail? I might still remember when I see your configuration.

**Comment by m1ch3lp3r3z** [comment]
Hi @kkesley, thank you for your quick reply. I'm trying to implement a lambda function that will receive data from a contact us form (application/x-www-form-urlencoded) and will return a 302 status code and Location header. My handler definition in serverless.yml looks like:

```
functions:
  contactUs:
    handler: go/bin/handlers/contact_us
    warmup:
      enabled: false
    events:
      - http:
          path: ${self:custom.apiVersion}/contact-us
          method: post
          cors: false
          integration: lambda
          response:
            statusCodes: 
              302:
                pattern: '' # Default response method
                headers:
                  Content-Type: "'text/html'"
                  Location: integration.response.header.location
```

Since I added the `lambda integration` I'm getting this error from the API Gateway:

`{"errorMessage":"json: cannot unmarshal object into Go struct field APIGatewayProxyRequest.body of type string","errorType":"UnmarshalTypeError"}`

The request is not even reaching my function so I'm guessing API Gateway is trying to receive the input as a JSON, but I fail to see where to change that.

Thank you!
